# name: Update S3 Bucket
# run-name: ${{ github.actor }} cloud resume

# #push on main branch
# on: 
#   push:
#     branches:
#       -main 

# jobs:
#   deployment:
#     runs-on: ubuntu-latest
#     steps:
#       - name: deploy
#       - uses: actions/checkout@master
#       - run: echo "hello"

# #autentication to bucket
#     environment:
#       name: AWS
#       AWS_S3BUCKET:

name: hello-world
'on': push
branchs: '-main'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"