name: S3-BUCKET

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo, S3 SYNC
        uses: actions/checkout@master
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
          
  - name: Authentication to bucket
    env:
      AWS_S3_BUCKET: "aws-cloud-resume"
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_REGION: 'us-east-1'
      SOURCE_DIRECTORY: 'awscloud'

      
    # runs:
    #   using: "docker"
    #   image: "Dockerfile"
    #   args:
    #     - ${{ inputs.AWS_ACCESS_KEY_ID }}
    #     - ${{ inputs.AWS_SECRET_ACCESS_KEY }}
    #     - ${{ inputs.AWS_S3_BUCKET }}
    #     - ${{ inputs.AWS_REGION }}
    #     - ${{ inputs.SOURCE_DIR }}
